name: Update Kernel Source
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at midnight (UTC)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "donVito007"
          git config --global user.email "frditc@gmail.com"
          git remote set-url origin https://github.com/donvito007/KernelSU_Thyme_SoundBeast.git

      - name: Get latest Linux stable version
        id: get_latest_version
        run: |
          latest_version=$(curl -s https://www.kernel.org/releases.json | jq -r '.[0].version')
          echo "::set-output name=latest_version::$latest_version"

      - name: Check if update is needed
        id: check_update
        run: |
          current_version=$(awk -F'"' '/VERSION =/ {print $2}' Makefile)
          latest_version=${{ steps.get_latest_version.outputs.latest_version }}
          if [[ "$current_version" == "$latest_version" ]]; then
            echo "No update available. Current version: $current_version"
            echo "::set-output name=update_available::false"
          else
            echo "Update available. Current version: $current_version, Latest version: $latest_version"
            echo "::set-output name=update_available::true"
          fi

      - name: Update kernel source
        if: steps.check_update.outputs.update_available == 'true'
        run: |
          git fetch origin
          git checkout main
          git merge upstream/main
          git push origin main

      - name: Notify update status
        if: always()
        run: |
          if [[ "${{ steps.check_update.outputs.update_available }}" == 'true' ]]; then
            echo "Kernel source has been updated to the latest version."
          else
            echo "No updates are available. Kernel source is already up-to-date."
          fi
