name: Update Kernel Source
on:
  workflow_dispatch:
    inputs:
      update:
        description: 'Update Kernel Source'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check latest linux-stable version
        id: check_version
        run: |
          latest_version=$(curl -s https://www.kernel.org/releases.json | jq -r '.latest_stable.version')
          echo "::set-output name=version::$latest_version"

      - name: Compare versions
        id: compare_versions
        run: |
          current_version=$(awk -F= '/^VERSION/ {gsub(/"/, "", $2); print $2}' Makefile)
          latest_version=${{ steps.check_version.outputs.version }}
          if [[ "$current_version" == "$latest_version" ]]; then
            echo "No update available. Current version: $current_version"
            echo "::set-output name=update_available::false"
          else
            echo "Update available. Current version: $current_version, Latest version: $latest_version"
            echo "::set-output name=update_available::true"
          fi
      - name: Update repository
        if: steps.compare_versions.outputs.update_available == 'true'
        run: |
          git config --global user.name "donVito007"
          git config --global user.email "frditc@gmail.com"
          git remote add origin https://github.com/donvito007/KernelSU_Thyme_SoundBeast.git
          git fetch origin
          git checkout master
          git merge upstream/master
          git push --quiet origin master
        env:
          GH_TOKEN: ${{ secrets.Local }}

      
