name: Update Kernel Source
on:
  workflow_dispatch:
    inputs:
      update:
        description: 'Update Kernel Source'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check latest linux-stable version
        id: check_version
        run: |
          latest_version=$(curl -s https://www.kernel.org/releases.json | jq -r '.latest_stable.version')
          echo "::set-output name=version::$latest_version"

      - name: Compare versions
        id: compare_versions
        run: |
          current_version=$(grep -Po '^VERSION = "\K[^"]+' Makefile)
          latest_version=${{ steps.check_version.outputs.version }}
          if [[ "$current_version" == "$latest_version" ]]; then
            echo "No update available. Current version: $current_version"
            echo "::set
